name: Compile and build FW

# Trigger the workflow on push or pull request on any branch
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      # Install common reqired packages: gcc, avr-libc, avrdude, python3, python3-pip
      run: sudo apt-get install -y gcc-avr binutils-avr avr-libc avrdude python3 python3-pip zip
    - name: Compile Prod (DEBUG=0, COMPACT=1)
      run: ./fbt COMPACT=1 DEBUG=0 updater_package
    - name: Upload prod artifact (TAR)
      uses: actions/upload-artifact@v2
      with:
        name: flipper-z-f7-update-Korai.tgz
        path: dist/f7-C/flipper-z-f7-update-Korai.tgz

